# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        include:
          - { os: ubuntu-20.04, arch: "linux/amd64", implementation: "tdlight" }
          #- { os: ubuntu-20.04, arch: "linux/amd64", implementation: "tdlib" }
    runs-on: ${{ matrix.os }}
    steps:
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
          echo ::set-output name=SOURCE_TAG_VERSION::${GITHUB_REF#refs/tags/v}
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Setup variables
        shell: bash
        run: |
          # ====== Variables
          export REVISION=${{ steps.branch_name.outputs.SOURCE_TAG_VERSION }}
          export IMPLEMENTATION_NAME=${{ matrix.implementation }}

          echo "REVISION=$REVISION" >> $GITHUB_ENV
          echo "IMPLEMENTATION_NAME=$IMPLEMENTATION_NAME" >> $GITHUB_ENV
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          server-id: mchv-release-distribution
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Build
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        shell: bash
        run: |
          echo "IMPLEMENTATION_NAME: $IMPLEMENTATION_NAME"

          source ./scripts/continuous-integration/github-workflows/only-compile-release.sh
      - name: Deploy to Maven (Release)
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        shell: bash
        run: |
          echo "REVISION: $REVISION"
          echo "IMPLEMENTATION_NAME: $IMPLEMENTATION_NAME"

          source ./scripts/continuous-integration/github-workflows/deploy-release.sh
        env:
          MAVEN_USERNAME: ${{ secrets.MCHV_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MCHV_TOKEN }}