# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - master
      - develop
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - { os: ubuntu-20.04, arch: "linux/amd64" }
    runs-on: ${{ matrix.os }}
    steps:
      - name: Branch name and revision
        id: branch_name
        run: |
          set -xeo pipefail
          
          export SOURCE_NAME="${GITHUB_REF#refs/*/}"
          export SOURCE_BRANCH="${GITHUB_REF#refs/heads/}"
          export SOURCE_TAG="${GITHUB_REF#refs/tags/}"
          export SOURCE_TAG_VERSION="${GITHUB_REF#refs/tags/v}"
          export REVISION="$SOURCE_TAG_VERSION"
          
          echo "SOURCE_TAG_VERSION=$SOURCE_TAG_VERSION" >> $GITHUB_ENV
          echo "REVISION=$REVISION" >> $GITHUB_ENV
          
          cat $GITHUB_ENV > github.env
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Set up JDK 17 (Snapshot)
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: 'maven'
          server-id: mchv-snapshot-distribution
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Build and deploy to Maven (Snapshot)
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        shell: bash
        run: |
          set -xeo pipefail

          mvn -B -f bom/pom.xml -P "java8,java17" clean deploy
          echo "Done."
        env:
          MAVEN_USERNAME: ${{ secrets.MCHV_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MCHV_TOKEN }}
      - name: Set up JDK 17 (Release)
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: 'maven'
          server-id: mchv-release-distribution
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Build and deploy to Maven (Release)
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        shell: bash
        run: |
          set -xeo pipefail
          echo "REVISION: $REVISION"
          
          mvn -B -f bom/pom.xml -Drevision="${REVISION}" -P "java8,java17" clean deploy
          echo "Done."
        env:
          MAVEN_USERNAME: ${{ secrets.MCHV_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MCHV_TOKEN }}